apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  namespace: llm-infra
  labels:
    app.kubernetes.io/part-of: synapse
    app.kubernetes.io/component: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: local-path
